const cardCategories = [
    'Gospel of Christ',
    'Lineage of Christ',
    'Prophecies of Christ',
    '10th Anniversary',
    '1st Edition',
    '1st Edition Unlimited',
    '2nd Edition',
    '2nd Edition Revised',
    '3rd Edition',
    'Angel Wars',
    'Apostles',
    'Cloud of Witnesses',
    'Disciples',
    'Early Church',
    'Faith of Our Fathers',
    'Fall of Man',
    'I',
    'J',
    'K Starter',
    'Kings',
    'L Starter',
    'Main',
    'Main Unlimited',
    'Patriarchs',
    'Persecuted Church',
    'Priests',
    'Promo',
    'Prophets',
    'Revelation of John',
    'Rock of Ages',
    'Thesaurus ex Preteritus',
    'Warriors',
    'Women'
  ];